id: A2DFAA4F5
title: XVII. Tatprāptivyavasthāpanā
type: translation
source_metadata:
  languages:
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:09:37.046762
  last_modified_at: 2022-03-01 21:09:37.046765
