id: A2DFAA4F5
title: VII. Pariṣkāra
type: translation
source_metadata:
  languages:
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:09:37.035696
  last_modified_at: 2022-03-01 21:09:37.035698
