id: A2DFAA4F5
title: '56th-62nd akṣaya: Saptabodhyaṅga'
type: translation
source_metadata:
  languages:
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:09:36.965081
  last_modified_at: 2022-03-01 21:09:36.965084
