id: A2DFAA4F5
title: XI. Saṃbhāramārga
type: translation
source_metadata:
  languages:
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:09:37.039352
  last_modified_at: 2022-03-01 21:09:37.039355
