id: A2DFAA4F5
title: I. Nidāna
type: translation
source_metadata:
  languages:
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:09:37.017681
  last_modified_at: 2022-03-01 21:09:37.017684
