id: A2DFAA4F5
title: '9th akṣaya: Dhyāna'
type: translation
source_metadata:
  languages:
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:09:37.014752
  last_modified_at: 2022-03-01 21:09:37.014755
