id: A2DFAA4F5
title: '63rd-70th akṣaya: Āryāṣṭāṅgamārga'
type: translation
source_metadata:
  languages:
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:09:36.971709
  last_modified_at: 2022-03-01 21:09:36.971713
